"""Shared fixtures: a synthetic mini-corpus so the whole API is testable
without the real Madrid data. Created at import time because app.config
reads environment variables once, at import."""
import csv
import os
import tempfile
from pathlib import Path

import pytest

# ---------------------------------------------------------------- corpus ---
_TMP = Path(tempfile.mkdtemp(prefix="ufwe-test-"))

SITES = [
    (0, 40.4691, -3.6428),
    (1, 40.4600, -3.6300),
    (2, 40.4520, -3.6180),
]

DAYS_IN_MONTH = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]


def _temp(h: int, base: float) -> float:
    """Diurnal cycle: min at 5h, max at 15h."""
    return round(base + 6.0 * ((h - 5) % 24) / 10.0, 1)


def make_epw(path: Path, base=15.0, city="MADRID_TEST", lat=40.46, lon=-3.64,
             elev=600.0, rh=45.0, wind=3.0, rad=200.0) -> None:
    """Write a minimal valid 8,760-row EPW."""
    lines = [
        f"LOCATION,{city},-,ESP,IWEC,082210,{lat},{lon},1.0,{elev}",
        "DESIGN CONDITIONS,1,Climate Design Data ASHRAE,,Heating,1,-4.1",
        "TYPICAL/EXTREME PERIODS,1,Summer - Week Hottest,7/1,7/31",
        "GROUND TEMPERATURES,1.0,1,2,3",
        "HOLIDAYS/DAYLIGHT SAVINGS,No,0,0,0",
        "COMMENTS 1,Synthetic file for tests",
        "COMMENTS 2,Generated by tests/conftest.py",
        "DATA PERIODS,1,1,Data Per,H,1,1/1,12/31",
    ]
    for m in range(1, 13):
        for day in range(1, DAYS_IN_MONTH[m - 1] + 1):
            for h in range(1, 25):
                t = _temp(h, base)
                # EPW data columns (0-indexed): 0 year, 1 month, 2 day,
                # 3 hour, 4 minute, 5 flags, 6 dry-bulb, 7 dew-point, 8 RH,
                # 9 pressure, 10-12 radiation extras, 13 global horz,
                # 14-19 more radiation fields, 20 wind direction, 21 wind speed.
                lines.append(
                    f"1983,{m},{day},{h},1,?9,{t},{t - 4.0},{rh},"
                    f"101300,10,0,0,{rad},0,0,0,0.0,0.0,0.0,270,{wind}"
                )
    path.write_text("\n".join(lines) + "\n", encoding="latin-1")


def write_corpus(root: Path) -> None:
    """locations.csv + 3 scenario folders; site 2 missing from midfuture."""
    with open(root / "locations.csv", "w", newline="") as fh:
        w = csv.writer(fh)
        w.writerow(["epwIndex", "latitude", "longitude"])
        for sid, lat, lon in SITES:
            w.writerow([sid, lat, lon])

    hist = root / "Historical_MostSevere"
    mid = root / "Midfuture MostSevere"
    fut = root / "FutureSevere_2084"
    for d in (hist, mid, fut):
        d.mkdir(parents=True)

    make_epw(hist / "0.epw", base=15.0)
    make_epw(hist / "1.epw", base=16.0)
    make_epw(hist / "2.epw", base=17.0)
    # midfuture: warmer, site 2 absent (fallback naming for site 1)
    make_epw(mid / "0_updated.epw", base=18.0)
    make_epw(mid / "1.epw", base=19.0)
    make_epw(fut / "0.epw", base=18.5)
    make_epw(fut / "1.epw", base=19.5)
    make_epw(fut / "2.epw", base=20.5)


write_corpus(_TMP)

# ---------------------------------------------------------------- env/env ---


@pytest.fixture(scope="session")
def client():
    """FastAPI TestClient against the synthetic corpus."""
    os.environ["UFWE_DATA_DIR"] = str(_TMP)
    os.environ["UFWE_CACHE_DIR"] = str(_TMP / "cache")
    os.environ["UFWE_DOWNLOAD_DIR"] = str(_TMP / "downloads")
    # LOCAL_DATA_DIR intentionally unset: read the corpus directly.
    import importlib
    import sys
    from pathlib import Path as _P

    sys.path.insert(0, str(_P(__file__).resolve().parent.parent))
    import app.main as main_mod

    importlib.reload(main_mod)
    main_mod._precompute_warming()               # synchronous: tiny corpus
    from fastapi.testclient import TestClient

    with TestClient(main_mod.app) as tc:
        yield tc
